/**
 * Real cigar catalog: well-known brands, lines, and vitolas that make up the
 * bulk of what sits in US humidors. Facts only (blend, sizes, origin); the
 * one-line descriptions are our own words. MSRP is an approximate US single
 * price and is only used to pre-fill store inventory forms.
 *
 * seedCatalog() is idempotent: it inserts any (brand, name) not already in
 * the cigars table and leaves existing rows untouched, so it is safe to run
 * on every boot. Run standalone with: node src/database/catalog.js
 */
'use strict';

const v = (name, length, ring_gauge, msrp) => ({ name, length, ring_gauge, msrp });

const NIC = 'Nicaragua', DR = 'Dominican Republic', HON = 'Honduras', CUBA = 'Cuba';

const CATALOG = [
  // ── Padrón ───────────────────────────────────────────────────────────────
  { brand: 'Padrón', name: '1964 Anniversary Series Natural', country: NIC, wrapper: 'Nicaraguan Habano (sun grown)', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 1994,
    flavor_notes: ['cocoa', 'coffee', 'cedar', 'earth'], description: 'Box-pressed benchmark from Padrón with tobacco aged four years. Rich cocoa and coffee with a smooth, even burn.',
    vitolas: [v('Principe', 4.5, 46, 15), v('Exclusivo', 5.5, 50, 20), v('Superior', 6.5, 42, 18), v('Monarca', 6.5, 46, 21), v('Torpedo', 6, 52, 24), v('Imperial', 6, 54, 24), v('Diplomatico', 7, 50, 27), v('Hermoso', 4, 56, 19)] },
  { brand: 'Padrón', name: '1964 Anniversary Series Maduro', country: NIC, wrapper: 'Nicaraguan Maduro', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 1994,
    flavor_notes: ['dark chocolate', 'espresso', 'pepper', 'earth'], description: 'The maduro version of the 1964, darker and sweeter with espresso and dark chocolate.',
    vitolas: [v('Principe', 4.5, 46, 15), v('Exclusivo', 5.5, 50, 20), v('Superior', 6.5, 42, 18), v('Monarca', 6.5, 46, 21), v('Torpedo', 6, 52, 24), v('Imperial', 6, 54, 24), v('Diplomatico', 7, 50, 27), v('Hermoso', 4, 56, 19)] },
  { brand: 'Padrón', name: '1926 Serie', country: NIC, wrapper: 'Nicaraguan Habano', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2002,
    flavor_notes: ['cocoa', 'leather', 'black pepper', 'cedar'], description: 'Padrón\'s top regular line, made with five-year-aged tobacco. Fuller and more complex than the 1964, natural or maduro.',
    vitolas: [v('No. 35', 4, 48, 22), v('No. 6', 4.75, 50, 26), v('No. 47', 5.5, 50, 29), v('No. 9', 5.25, 56, 31), v('No. 2', 5.5, 52, 30), v('No. 40', 6.5, 54, 34), v('No. 1', 6.75, 54, 36)] },
  { brand: 'Padrón', name: 'Series (Thousands)', country: NIC, wrapper: 'Nicaraguan (natural or maduro)', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium', year_introduced: 1964,
    flavor_notes: ['cocoa', 'coffee', 'earth', 'nuts'], description: 'The everyday Padrón. Unassuming look, consistent construction, and honest Nicaraguan flavor at a fair price.',
    vitolas: [v('Corticos', 4.5, 35, 5), v('Delicias', 4.875, 46, 7), v('Londres', 5.5, 42, 7), v('2000', 5, 50, 8), v('3000', 5.5, 52, 9), v('4000', 6.5, 54, 10), v('5000', 5.5, 56, 10), v('6000', 5.5, 52, 10), v('7000', 6.25, 60, 11), v('Churchill', 6.875, 46, 9), v('Ambassador', 6.875, 42, 8), v('Executive', 7.5, 50, 11), v('Magnum', 9, 50, 13)] },
  { brand: 'Padrón', name: 'Family Reserve', country: NIC, wrapper: 'Nicaraguan (natural or maduro)', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2008,
    flavor_notes: ['dark chocolate', 'coffee', 'spice', 'cream'], description: 'Ten-year-aged tobacco in numbered sizes released for family milestones. The most refined Padrón you can buy regularly.',
    vitolas: [v('No. 85', 5.25, 50, 32), v('No. 50', 5, 54, 32), v('No. 44', 6, 52, 35), v('No. 45', 6, 52, 35), v('No. 46', 5.5, 56, 35)] },
  { brand: 'Padrón', name: 'Dámaso', country: NIC, wrapper: 'Ecuadorian Connecticut', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'mild-medium', year_introduced: 2015,
    flavor_notes: ['cream', 'cedar', 'nuts', 'white pepper'], description: 'Padrón\'s only Connecticut-wrapped cigar, named for the founder\'s grandfather. Creamy and mild but still unmistakably Padrón.',
    vitolas: [v('No. 8', 5, 46, 14), v('No. 12', 5, 50, 15), v('No. 15', 6, 52, 17), v('No. 17', 7, 54, 19)] },

  // ── Arturo Fuente ────────────────────────────────────────────────────────
  { brand: 'Arturo Fuente', name: 'Hemingway', country: DR, wrapper: 'Cameroon', binder: 'Dominican', filler: 'Dominican', strength: 'medium', year_introduced: 1983,
    flavor_notes: ['cedar', 'sweet spice', 'nuts', 'cream'], description: 'Figurado line that revived the perfecto shape. Sweet Cameroon wrapper, a slow build, and legendary consistency.',
    vitolas: [v('Short Story', 4, 49, 9), v('Best Seller', 4.5, 55, 10), v('Signature', 6, 47, 11), v('Classic', 7, 48, 12), v('Work of Art', 4.875, 60, 12), v('Masterpiece', 9, 52, 20)] },
  { brand: 'Arturo Fuente', name: 'Fuente Fuente OpusX', country: DR, wrapper: 'Dominican Rosado (Chateau de la Fuente)', binder: 'Dominican', filler: 'Dominican', strength: 'full', year_introduced: 1995,
    flavor_notes: ['red pepper', 'cedar', 'leather', 'sweet spice'], description: 'The first Dominican puro that proved Dominican wrapper could be grown. Allocated, aged, and always in demand.',
    vitolas: [v('Perfexcion No. 5', 4.875, 40, 22), v('Perfexcion No. 4', 5.125, 43, 24), v('Fuente Fuente', 5.625, 46, 27), v('Robusto', 5.25, 50, 30), v('Perfexcion X', 6.25, 48, 33), v('Perfexcion No. 2', 6.25, 52, 36), v('Petit Lancero', 6.25, 38, 26), v('Reserva d\'Chateau', 7, 48, 38), v('Double Corona', 7.625, 49, 42)] },
  { brand: 'Arturo Fuente', name: 'Don Carlos', country: DR, wrapper: 'Cameroon', binder: 'Dominican', filler: 'Dominican', strength: 'medium', year_introduced: 1976,
    flavor_notes: ['cedar', 'sweet tobacco', 'nuts', 'baking spice'], description: 'Carlos Fuente Sr.\'s personal blend. Aged Cameroon wrapper over Dominican filler, elegant and balanced.',
    vitolas: [v('No. 4', 5.125, 43, 12), v('No. 3', 5.5, 44, 13), v('Robusto', 5.25, 50, 15), v('Double Robusto', 5.75, 52, 17), v('Belicoso', 5.5, 52, 17), v('No. 2', 6, 55, 18), v('Presidente', 6.5, 50, 18)] },
  { brand: 'Arturo Fuente', name: 'Gran Reserva', country: DR, wrapper: 'Connecticut Shade or Broadleaf Maduro', binder: 'Dominican', filler: 'Dominican', strength: 'mild-medium', year_introduced: 1912,
    flavor_notes: ['cedar', 'cream', 'toast', 'mild spice'], description: 'The classic Fuente line in natural and maduro, including the 8-5-8 and Chateau Fuente. Great value and everywhere.',
    vitolas: [v('Exquisitos', 4.5, 33, 4), v('Petit Corona', 5, 38, 5), v('Rothschild', 4.5, 50, 6), v('Chateau Fuente', 4.5, 50, 7), v('Brevas Royale', 5.5, 42, 5), v('Cuban Corona', 5.25, 45, 6), v('Curly Head', 6.5, 43, 5), v('8-5-8', 6, 47, 7), v('Double Chateau', 6.75, 50, 9), v('Churchill', 7.25, 48, 8)] },

  // ── Davidoff ─────────────────────────────────────────────────────────────
  { brand: 'Davidoff', name: 'Signature', country: DR, wrapper: 'Ecuadorian Connecticut', binder: 'Dominican', filler: 'Dominican', strength: 'mild', year_introduced: 1990,
    flavor_notes: ['cream', 'cedar', 'nuts', 'honey'], description: 'Formerly the Classic series. Refined and mild, the definition of a Davidoff.',
    vitolas: [v('1000', 4.625, 34, 15), v('2000', 5, 43, 19), v('No. 2', 6, 38, 21), v('4000', 6.125, 42, 23), v('6000', 5.5, 48, 26)] },
  { brand: 'Davidoff', name: 'Aniversario', country: DR, wrapper: 'Ecuadorian Connecticut', binder: 'Dominican', filler: 'Dominican', strength: 'mild-medium', year_introduced: 1986,
    flavor_notes: ['cream', 'cedar', 'toast', 'white pepper'], description: 'Larger formats with a touch more body than the Signature. The Special R and No. 3 are staples.',
    vitolas: [v('Entreacto', 3.5, 43, 14), v('Short Perfecto', 4.875, 52, 27), v('Special R', 4.875, 50, 26), v('No. 3', 6, 50, 32), v('Special T', 6, 52, 33), v('Double R', 7.5, 50, 40)] },
  { brand: 'Davidoff', name: 'Nicaragua', country: NIC, wrapper: 'Nicaraguan Habano (Jalapa)', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium', year_introduced: 2013,
    flavor_notes: ['pepper', 'cocoa', 'cedar', 'sweet spice'], description: 'Davidoff\'s first Nicaraguan puro. The house elegance with real Nicaraguan spice.',
    vitolas: [v('Primeros', 4, 33, 10), v('Short Corona', 3.75, 46, 15), v('Robusto', 5, 50, 20), v('Box Pressed Robusto', 5, 48, 21), v('Toro', 5.5, 54, 23), v('Box Pressed Toro', 6, 52, 24), v('Diadema', 6.5, 50, 27)] },
  { brand: 'Davidoff', name: 'Winston Churchill', country: DR, wrapper: 'Ecuadorian Habano', binder: 'Mexican', filler: 'Dominican and Nicaraguan', strength: 'medium', year_introduced: 2015,
    flavor_notes: ['cedar', 'nuts', 'cream', 'spice'], description: 'A medium-bodied multi-country blend named for Davidoff\'s most famous customer.',
    vitolas: [v('Petit Corona', 4, 41, 14), v('Robusto', 5, 52, 22), v('Belicoso', 5.5, 52, 24), v('Toro', 6, 54, 25), v('Churchill', 7, 48, 26)] },
  { brand: 'Davidoff', name: 'Winston Churchill The Late Hour', country: DR, wrapper: 'Ecuadorian Habano', binder: 'Mexican', filler: 'Dominican and Nicaraguan (scotch-cask aged)', strength: 'medium-full', year_introduced: 2017,
    flavor_notes: ['dark chocolate', 'oak', 'dried fruit', 'pepper'], description: 'Filler aged in single-malt casks. Darker, richer, and built for after dinner.',
    vitolas: [v('Robusto', 5, 52, 25), v('Toro', 6, 54, 28), v('Churchill', 7, 48, 29)] },
  { brand: 'Davidoff', name: 'Millennium', country: DR, wrapper: 'Ecuadorian Connecticut (sun grown)', binder: 'Dominican', filler: 'Dominican', strength: 'medium', year_introduced: 2000,
    flavor_notes: ['toast', 'leather', 'pepper', 'cedar'], description: 'The fuller Davidoff, built around a darker sun-grown Connecticut wrapper.',
    vitolas: [v('Short Robusto', 4.25, 52, 22), v('Robusto', 5.25, 50, 26), v('Lonsdale', 6, 43, 25), v('Piramides', 6.125, 52, 32), v('Churchill', 7, 48, 32)] },
  { brand: 'Davidoff', name: 'Yamasá', country: DR, wrapper: 'Dominican Yamasá', binder: 'Dominican', filler: 'Dominican and Nicaraguan', strength: 'medium-full', year_introduced: 2016,
    flavor_notes: ['earth', 'pepper', 'dark chocolate', 'wood'], description: 'Wrapper grown in a Dominican region once thought unsuitable for tobacco. Earthy and the strongest of the core lines.',
    vitolas: [v('Petit Churchill', 4, 48, 17), v('Robusto', 5, 50, 23), v('Toro', 6, 54, 27), v('Piramides', 6.125, 52, 30)] },

  // ── Drew Estate ──────────────────────────────────────────────────────────
  { brand: 'Drew Estate', name: 'Liga Privada No. 9', country: NIC, wrapper: 'Connecticut Broadleaf Oscuro', binder: 'Brazilian Mata Fina', filler: 'Nicaraguan and Honduran', strength: 'full', year_introduced: 2007,
    flavor_notes: ['dark chocolate', 'espresso', 'earth', 'pepper'], description: 'Started as a private blend for the founders and became a cult full-bodied favorite. Oily broadleaf and a thick, rich smoke.',
    vitolas: [v('Flying Pig', 4.125, 60, 20), v('Robusto', 5, 54, 16), v('Toro', 6, 52, 17), v('Belicoso', 6, 52, 18), v('Corona Doble', 7, 54, 20)] },
  { brand: 'Drew Estate', name: 'Liga Privada T52', country: NIC, wrapper: 'Connecticut Habano (stalk cut)', binder: 'Brazilian Mata Fina', filler: 'Nicaraguan and Honduran', strength: 'full', year_introduced: 2009,
    flavor_notes: ['pepper', 'leather', 'cocoa', 'cedar'], description: 'Stalk-cut, sun-cured wrapper gives the T52 more spice and leather than the No. 9.',
    vitolas: [v('Flying Pig', 4.125, 60, 21), v('Robusto', 5, 54, 17), v('Toro', 6, 52, 18), v('Belicoso', 6, 52, 19), v('Corona Doble', 7, 54, 21)] },
  { brand: 'Drew Estate', name: 'Undercrown Maduro', country: NIC, wrapper: 'Mexican San Andrés Maduro', binder: 'Connecticut Stalk Cut', filler: 'Nicaraguan and Brazilian', strength: 'medium-full', year_introduced: 2011,
    flavor_notes: ['cocoa', 'coffee', 'earth', 'sweet spice'], description: 'Created by the Liga Privada rollers for themselves. A more affordable cousin with San Andrés depth.',
    vitolas: [v('Corona', 5.625, 46, 9), v('Robusto', 5, 54, 10), v('Gran Toro', 6, 52, 11), v('Belicoso', 6, 52, 11), v('Gordito', 6, 60, 12), v('Corona Doble', 7, 54, 12), v('Flying Pig', 4.125, 60, 14)] },
  { brand: 'Drew Estate', name: 'Undercrown Shade', country: NIC, wrapper: 'Ecuadorian Connecticut', binder: 'Sumatra', filler: 'Dominican and Nicaraguan', strength: 'mild-medium', year_introduced: 2015,
    flavor_notes: ['cream', 'cedar', 'nuts', 'honey'], description: 'The Connecticut version of Undercrown: creamy, smooth, and easy to smoke any time of day.',
    vitolas: [v('Corona', 5.625, 46, 9), v('Robusto', 5, 54, 10), v('Gran Toro', 6, 52, 11), v('Belicoso', 6, 52, 11), v('Gordito', 6, 60, 12), v('Corona Doble', 7, 54, 12)] },
  { brand: 'Drew Estate', name: 'Undercrown Sun Grown', country: NIC, wrapper: 'Ecuadorian Sumatra', binder: 'Connecticut Stalk Cut', filler: 'Nicaraguan', strength: 'full', year_introduced: 2017,
    flavor_notes: ['pepper', 'cedar', 'earth', 'dark fruit'], description: 'The boldest Undercrown, with a sun-grown Sumatra wrapper and more pepper throughout.',
    vitolas: [v('Robusto', 5, 54, 10), v('Gran Toro', 6, 52, 11), v('Belicoso', 6, 52, 11), v('Gordito', 6, 60, 12), v('Corona Doble', 7, 54, 12), v('Flying Pig', 4.125, 60, 14)] },
  { brand: 'Drew Estate', name: 'Herrera Esteli Habano', country: NIC, wrapper: 'Ecuadorian Habano', binder: 'Honduran', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2013,
    flavor_notes: ['cedar', 'pepper', 'cream', 'nuts'], description: 'Willy Herrera\'s Cuban-style blend for Drew Estate. Refined, spicy, and traditionally sized.',
    vitolas: [v('Short Corona Gorda', 5.75, 46, 10), v('Toro Especial', 6, 44, 11), v('Lonsdale Deluxe', 6.5, 44, 11), v('Robusto Extra', 5.5, 54, 11), v('Piramide Fino', 6, 52, 12)] },
  { brand: 'Acid', name: 'Kuba Kuba', country: NIC, wrapper: 'Sumatra', binder: 'Nicaraguan', filler: 'Nicaraguan (infused)', strength: 'mild-medium', year_introduced: 1999,
    flavor_notes: ['sweet', 'floral', 'herbal', 'cedar'], description: 'Drew Estate\'s infused best seller. Sweet, aromatic, and unapologetically different.',
    vitolas: [v('Kuba Kuba', 5, 54, 9), v('Kuba Kuba Maduro', 5, 54, 9)] },
  { brand: 'Acid', name: 'Blondie', country: NIC, wrapper: 'Connecticut', binder: 'Nicaraguan', filler: 'Nicaraguan (infused)', strength: 'mild', year_introduced: 1999,
    flavor_notes: ['sweet', 'vanilla', 'floral'], description: 'Small, sweet, and mild. The gateway infused cigar.',
    vitolas: [v('Blondie', 4, 38, 6), v('Blondie Belicoso', 5, 54, 9)] },

  // ── Oliva ────────────────────────────────────────────────────────────────
  { brand: 'Oliva', name: 'Serie V', country: NIC, wrapper: 'Nicaraguan Habano (sun grown)', binder: 'Nicaraguan', filler: 'Nicaraguan (Jalapa ligero)', strength: 'full', year_introduced: 2007,
    flavor_notes: ['pepper', 'cocoa', 'leather', 'earth'], description: 'Jalapa ligero gives the Serie V its strength without harshness. A modern Nicaraguan classic.',
    vitolas: [v('Double Robusto', 5, 54, 10), v('Belicoso', 5, 54, 10), v('Torpedo', 6, 56, 12), v('Double Toro', 6, 60, 12), v('Churchill Extra', 7, 52, 12), v('Lancero', 7, 38, 10)] },
  { brand: 'Oliva', name: 'Serie V Melanio', country: NIC, wrapper: 'Ecuadorian Sumatra', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2012,
    flavor_notes: ['coffee', 'cedar', 'cream', 'sweet spice'], description: 'Box-pressed tribute to Melanio Oliva. Cigar Aficionado\'s Cigar of the Year in 2014.',
    vitolas: [v('Robusto', 5, 52, 14), v('Figurado', 6.5, 52, 16), v('Torpedo', 6.5, 52, 16), v('Churchill', 7, 50, 17), v('Double Toro', 6, 60, 17)] },
  { brand: 'Oliva', name: 'Serie V Melanio Maduro', country: NIC, wrapper: 'Mexican San Andrés Maduro', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2014,
    flavor_notes: ['dark chocolate', 'coffee', 'earth', 'spice'], description: 'The Melanio blend under a San Andrés maduro wrapper.',
    vitolas: [v('Robusto', 5, 52, 15), v('Torpedo', 6.5, 52, 17), v('Churchill', 7, 50, 18), v('Double Toro', 6, 60, 18)] },
  { brand: 'Oliva', name: 'Serie O', country: NIC, wrapper: 'Nicaraguan Habano (sun grown)', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium', year_introduced: 2002,
    flavor_notes: ['cedar', 'earth', 'coffee', 'mild spice'], description: 'Oliva\'s medium-bodied Nicaraguan puro. Reliable, affordable, and easy to recommend.',
    vitolas: [v('Robusto', 5, 50, 8), v('Toro', 6, 50, 9), v('Torpedo', 6, 52, 9), v('Churchill', 7, 50, 9), v('Double Toro', 6, 60, 10)] },
  { brand: 'Oliva', name: 'Serie G', country: NIC, wrapper: 'Cameroon', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium', year_introduced: 2002,
    flavor_notes: ['sweet spice', 'cedar', 'nuts', 'cocoa'], description: 'Cameroon-wrapped Oliva with a sweeter, spicier profile.',
    vitolas: [v('Robusto', 4.5, 50, 7), v('Belicoso', 5, 52, 8), v('Toro', 6, 50, 8), v('Torpedo', 6, 52, 8), v('Churchill', 7, 50, 9)] },
  { brand: 'Oliva', name: 'Connecticut Reserve', country: NIC, wrapper: 'Ecuadorian Connecticut', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'mild-medium', year_introduced: 2007,
    flavor_notes: ['cream', 'cedar', 'nuts', 'honey'], description: 'A Connecticut wrapper over Nicaraguan filler. Mild but not boring.',
    vitolas: [v('Robusto', 5, 50, 8), v('Toro', 6, 50, 9), v('Torpedo', 6, 52, 9), v('Churchill', 7, 50, 9)] },
  { brand: 'Nub', name: 'Habano', country: NIC, wrapper: 'Nicaraguan Habano', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2008,
    flavor_notes: ['pepper', 'cedar', 'earth', 'coffee'], description: 'Short and fat by design, so you start the smoke in the sweet spot. From Oliva.',
    vitolas: [v('460', 4, 60, 8), v('358', 3.75, 58, 7), v('464T', 4, 64, 9)] },
  { brand: 'Nub', name: 'Connecticut', country: NIC, wrapper: 'Ecuadorian Connecticut', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'mild-medium', year_introduced: 2008,
    flavor_notes: ['cream', 'cedar', 'nuts'], description: 'The mild Nub. Creamy Connecticut in the signature stubby format.',
    vitolas: [v('460', 4, 60, 8), v('358', 3.75, 58, 7)] },

  // ── My Father ────────────────────────────────────────────────────────────
  { brand: 'My Father', name: 'Le Bijou 1922', country: NIC, wrapper: 'Nicaraguan Habano Oscuro', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2009,
    flavor_notes: ['pepper', 'dark chocolate', 'earth', 'leather'], description: 'Named for Don Pepin Garcia\'s father. The box-pressed torpedo was Cigar of the Year in 2015.',
    vitolas: [v('Petit Robusto', 4.5, 50, 10), v('Grand Robusto', 5.5, 54, 12), v('Torpedo Box Press', 6.125, 52, 13), v('Toro', 6, 54, 13), v('Churchill', 7, 50, 14), v('Toro Gordo', 6, 60, 14)] },
  { brand: 'My Father', name: 'Flor de las Antillas', country: NIC, wrapper: 'Nicaraguan (sun grown)', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2012,
    flavor_notes: ['cedar', 'sweet spice', 'coffee', 'cream'], description: 'Box-pressed, sun-grown, and balanced. Cigar of the Year in 2012.',
    vitolas: [v('Robusto', 5, 50, 9), v('Toro', 6, 52, 10), v('Belicoso', 5.5, 52, 10), v('Toro Gordo', 6.5, 56, 11)] },
  { brand: 'My Father', name: 'The Judge', country: NIC, wrapper: 'Ecuadorian Sumatra', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2016,
    flavor_notes: ['pepper', 'cocoa', 'wood', 'earth'], description: 'A thick, full-bodied Sumatra-wrapped blend for people who like a punch.',
    vitolas: [v('Grand Robusto', 5, 60, 13), v('Toro Fino', 6, 52, 13), v('Toro Gordo', 6, 56, 14)] },

  // ── Ashton / La Aroma de Cuba ────────────────────────────────────────────
  { brand: 'Ashton', name: 'Classic', country: DR, wrapper: 'Connecticut Shade', binder: 'Dominican', filler: 'Dominican', strength: 'mild', year_introduced: 1985,
    flavor_notes: ['cream', 'cedar', 'nuts', 'toast'], description: 'Made by Fuente for Ashton. The gold standard for a mild Connecticut.',
    vitolas: [v('Cordial', 5, 30, 8), v('Panetela', 6, 36, 9), v('Corona', 5.5, 44, 10), v('Magnum', 5, 50, 11), v('8-9-8', 6.5, 44, 11), v('Double Magnum', 6, 50, 12), v('Prime Minister', 6.875, 48, 13), v('Churchill', 7.5, 52, 14)] },
  { brand: 'Ashton', name: 'VSG (Virgin Sun Grown)', country: DR, wrapper: 'Ecuadorian Sun Grown', binder: 'Dominican', filler: 'Dominican', strength: 'full', year_introduced: 1999,
    flavor_notes: ['pepper', 'leather', 'cedar', 'coffee'], description: 'Ashton\'s full-bodied line with a wrapper grown on Carlos Fuente\'s Ecuadorian farm.',
    vitolas: [v('Tres Mystique', 4.375, 44, 11), v('Robusto', 5.5, 50, 14), v('Corona Gorda', 5.75, 46, 13), v('Belicoso No. 1', 5.25, 52, 15), v('Torpedo', 6.5, 52, 16), v('Wizard', 6, 56, 16), v('Illusion', 6.5, 44, 14), v('Sorcerer', 7, 49, 17), v('Spellbound', 7.5, 54, 18)] },
  { brand: 'Ashton', name: 'Cabinet Selection', country: DR, wrapper: 'Connecticut Shade', binder: 'Dominican', filler: 'Dominican', strength: 'mild-medium', year_introduced: 1988,
    flavor_notes: ['cream', 'cedar', 'sweet tobacco', 'nuts'], description: 'Longer-aged tobaccos than the Classic, with a touch more body.',
    vitolas: [v('Tres Petite', 4.5, 44, 10), v('No. 3', 6, 46, 13), v('No. 2', 7, 46, 14), v('No. 8', 7, 49, 15), v('No. 10', 7.5, 52, 17)] },
  { brand: 'Ashton', name: 'Aged Maduro', country: DR, wrapper: 'Connecticut Broadleaf Maduro', binder: 'Dominican', filler: 'Dominican', strength: 'medium', year_introduced: 1990,
    flavor_notes: ['cocoa', 'sweet earth', 'coffee', 'cedar'], description: 'A smooth, sweet broadleaf maduro over Dominican filler.',
    vitolas: [v('No. 10', 5, 50, 11), v('No. 20', 5.5, 44, 11), v('No. 30', 6.75, 44, 12), v('No. 40', 6, 50, 13), v('No. 50', 7, 48, 14), v('No. 60', 7.5, 52, 15)] },
  { brand: 'Ashton', name: 'Heritage Puro Sol', country: DR, wrapper: 'Cameroon (sun grown)', binder: 'Dominican', filler: 'Dominican', strength: 'medium', year_introduced: 2007,
    flavor_notes: ['sweet spice', 'cedar', 'nuts', 'leather'], description: 'A sun-grown Cameroon wrapper gives this one more spice than the Classic.',
    vitolas: [v('Robusto', 5.5, 50, 12), v('Corona Gorda', 5.75, 46, 12), v('Belicoso', 5.5, 52, 13), v('Churchill', 7, 49, 14)] },
  { brand: 'Ashton', name: 'Symmetry', country: DR, wrapper: 'Ecuadorian Habano', binder: 'Dominican', filler: 'Dominican and Nicaraguan', strength: 'medium-full', year_introduced: 2015,
    flavor_notes: ['pepper', 'cedar', 'cream', 'coffee'], description: 'Ashton\'s first blend to mix Nicaraguan and Dominican filler.',
    vitolas: [v('Robusto', 5.5, 54, 15), v('Belicoso', 6.125, 52, 16), v('Prism', 6.5, 54, 17)] },
  { brand: 'La Aroma de Cuba', name: 'Original', country: NIC, wrapper: 'Connecticut Broadleaf', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2008,
    flavor_notes: ['cocoa', 'earth', 'pepper', 'coffee'], description: 'Made by Pepin Garcia for Ashton. Broadleaf over Nicaraguan filler at an everyday price.',
    vitolas: [v('Corona', 5.5, 44, 7), v('Robusto', 5, 54, 8), v('Monarch', 6, 54, 9), v('Churchill', 7, 50, 9)] },
  { brand: 'La Aroma de Cuba', name: 'Mi Amor', country: NIC, wrapper: 'Mexican San Andrés', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2010,
    flavor_notes: ['dark chocolate', 'espresso', 'sweet spice', 'earth'], description: 'Box-pressed San Andrés blend that landed on Cigar Aficionado\'s Top 25 several times.',
    vitolas: [v('Robusto', 5, 50, 9), v('Belicoso', 5.5, 54, 10), v('Churchill', 6.5, 50, 10), v('Valentino', 5.75, 58, 11)] },

  // ── General Cigar: Macanudo, Partagas, Cohiba, Punch, Hoyo, La Gloria, CAO ─
  { brand: 'Macanudo', name: 'Café', country: DR, wrapper: 'Connecticut Shade', binder: 'Mexican San Andrés', filler: 'Dominican and Mexican', strength: 'mild', year_introduced: 1968,
    flavor_notes: ['cream', 'cedar', 'toast', 'nuts'], description: 'The best-selling premium cigar in America for decades. Mild, smooth, and everywhere.',
    vitolas: [v('Ascot', 4.19, 32, 4), v('Portofino', 7, 34, 8), v('Duke of Devon', 5.5, 42, 8), v('Hampton Court', 5.75, 43, 8), v('Baron de Rothschild', 6.5, 42, 9), v('Hyde Park', 5.5, 49, 9), v('Prince Philip', 7.5, 49, 11)] },
  { brand: 'Macanudo', name: 'Maduro', country: DR, wrapper: 'Connecticut Broadleaf Maduro', binder: 'Mexican San Andrés', filler: 'Dominican and Mexican', strength: 'medium', year_introduced: 1975,
    flavor_notes: ['cocoa', 'sweet earth', 'coffee'], description: 'The Café blend under a broadleaf maduro wrapper.',
    vitolas: [v('Duke of Devon', 5.5, 42, 8), v('Hampton Court', 5.75, 43, 8), v('Hyde Park', 5.5, 49, 9), v('Prince Philip', 7.5, 49, 11)] },
  { brand: 'Macanudo', name: 'Inspirado Orange', country: HON, wrapper: 'Honduran Habano Rosado', binder: 'Connecticut Broadleaf', filler: 'Nicaraguan, Honduran, and Dominican', strength: 'medium', year_introduced: 2016,
    flavor_notes: ['cedar', 'pepper', 'coffee', 'sweet spice'], description: 'The Macanudo for people who think Macanudo is too mild.',
    vitolas: [v('Robusto', 5, 50, 7), v('Toro', 6, 50, 8), v('Churchill', 7, 50, 8), v('Gigante', 6, 60, 9)] },
  { brand: 'Macanudo', name: 'Inspirado Black', country: HON, wrapper: 'Mexican San Andrés Maduro', binder: 'Connecticut Broadleaf', filler: 'Nicaraguan and Honduran', strength: 'full', year_introduced: 2017,
    flavor_notes: ['dark chocolate', 'pepper', 'earth', 'coffee'], description: 'The darkest, strongest Macanudo.',
    vitolas: [v('Robusto', 5, 50, 7), v('Toro', 6, 50, 8), v('Churchill', 7, 50, 8), v('Gigante', 6, 60, 9)] },
  { brand: 'Partagas', name: 'Original', country: DR, wrapper: 'Cameroon', binder: 'Mexican San Andrés', filler: 'Dominican and Mexican', strength: 'medium', year_introduced: 1978,
    flavor_notes: ['sweet spice', 'cedar', 'earth', 'leather'], description: 'The Dominican Partagas with a Cameroon wrapper. A traditionalist\'s cigar.',
    vitolas: [v('No. 2', 5.75, 43, 9), v('Robusto', 4.5, 49, 9), v('Naturales', 5.5, 50, 10), v('Almirantes', 6.25, 47, 11), v('No. 10', 7.5, 49, 13)] },
  { brand: 'Partagas', name: 'Black Label', country: DR, wrapper: 'Connecticut Medio Tiempo (sun grown)', binder: 'Dominican', filler: 'Dominican and Nicaraguan', strength: 'full', year_introduced: 2001,
    flavor_notes: ['pepper', 'earth', 'dark chocolate', 'leather'], description: 'The full-bodied Partagas with a rare sun-grown Connecticut wrapper.',
    vitolas: [v('Bravo', 4.5, 54, 9), v('Clasico', 5.25, 54, 10), v('Magnifico', 6, 54, 11), v('Gigante', 6, 60, 12), v('Piramide', 7, 54, 13)] },
  { brand: 'Cohiba', name: 'Red Dot', country: DR, wrapper: 'Cameroon', binder: 'Indonesian Jember', filler: 'Dominican', strength: 'medium', year_introduced: 1997,
    flavor_notes: ['cedar', 'sweet spice', 'cream', 'nuts'], description: 'The Dominican Cohiba sold in the US, recognizable by the red dot in the O.',
    vitolas: [v('Corona', 5.5, 42, 15), v('Robusto', 5, 49, 18), v('Toro', 6, 50, 20), v('Lonsdale Grande', 6.25, 47, 20), v('Triangulo', 6, 54, 22), v('Churchill', 7, 49, 22)] },
  { brand: 'Cohiba', name: 'Nicaragua', country: NIC, wrapper: 'Honduran Colorado Oscuro', binder: 'Nicaraguan Jalapa', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2014,
    flavor_notes: ['pepper', 'cocoa', 'cedar', 'earth'], description: 'The first Nicaraguan-made Cohiba, fuller and spicier than the Red Dot.',
    vitolas: [v('N45', 5.5, 45, 15), v('N50', 5, 50, 16), v('N54', 6, 54, 18), v('N60', 6, 60, 20)] },
  { brand: 'Punch', name: 'Original', country: HON, wrapper: 'Ecuadorian Sumatra', binder: 'Connecticut Broadleaf', filler: 'Honduran, Nicaraguan, and Dominican', strength: 'medium-full', year_introduced: 1969,
    flavor_notes: ['pepper', 'cedar', 'earth', 'sweet tobacco'], description: 'The Honduran Punch. Spicy, old school, and a great value in the Rothschild.',
    vitolas: [v('Rothschild', 4.5, 50, 6), v('Elites', 5.25, 45, 6), v('Café Royale', 5.625, 44, 6), v('Magnum', 5.25, 54, 7), v('Pita', 6.125, 50, 7), v('Double Corona', 6.75, 48, 8)] },
  { brand: 'Hoyo de Monterrey', name: 'Excalibur', country: HON, wrapper: 'Connecticut Shade', binder: 'Connecticut Broadleaf', filler: 'Honduran, Dominican, and Nicaraguan', strength: 'medium', year_introduced: 1987,
    flavor_notes: ['cedar', 'cream', 'nuts', 'mild spice'], description: 'The upscale Hoyo, aged longer and wrapped in Connecticut shade.',
    vitolas: [v('No. 5', 6.25, 45, 8), v('No. 4', 5.625, 46, 8), v('Epicure', 5.25, 50, 8), v('No. 3', 6.125, 48, 9), v('No. 2', 6.75, 47, 9), v('No. 1', 7.25, 54, 10)] },
  { brand: 'Hoyo de Monterrey', name: 'Original', country: HON, wrapper: 'Ecuadorian Sumatra', binder: 'Connecticut Broadleaf', filler: 'Honduran, Nicaraguan, and Dominican', strength: 'medium-full', year_introduced: 1965,
    flavor_notes: ['pepper', 'earth', 'cedar', 'leather'], description: 'The classic Honduran Hoyo, with a bit more bite than the Excalibur.',
    vitolas: [v('Rothschild', 4.5, 50, 6), v('Churchill', 6.25, 45, 7), v('Governor', 6.125, 50, 7), v('Double Corona', 6.75, 48, 8), v('Sultan', 7.25, 54, 9)] },
  { brand: 'La Gloria Cubana', name: 'Classic', country: DR, wrapper: 'Ecuadorian Sumatra', binder: 'Nicaraguan', filler: 'Dominican and Nicaraguan', strength: 'medium-full', year_introduced: 1972,
    flavor_notes: ['cedar', 'pepper', 'earth', 'sweet spice'], description: 'Ernesto Carrillo\'s original El Credito blend. The Wavell is a Little Havana icon.',
    vitolas: [v('Wavell', 5, 50, 7), v('Corona Gorda', 6, 52, 8), v('Churchill', 7, 50, 9), v('Soberano', 8, 52, 10)] },
  { brand: 'La Gloria Cubana', name: 'Serie R', country: DR, wrapper: 'Ecuadorian Sumatra', binder: 'Nicaraguan', filler: 'Dominican and Nicaraguan', strength: 'full', year_introduced: 1999,
    flavor_notes: ['pepper', 'leather', 'earth', 'cocoa'], description: 'Big ring gauges and a fuller blend, in natural or maduro.',
    vitolas: [v('No. 4', 4.875, 52, 8), v('No. 5', 5.5, 54, 9), v('No. 6', 5.875, 60, 10), v('No. 7', 7, 58, 11)] },
  { brand: 'CAO', name: 'Flathead', country: NIC, wrapper: 'Connecticut Broadleaf', binder: 'Connecticut Habano', filler: 'Nicaraguan', strength: 'full', year_introduced: 2013,
    flavor_notes: ['dark chocolate', 'pepper', 'earth', 'coffee'], description: 'Box-pressed with a flat head, named after hot-rod engines. Big, dark, and full.',
    vitolas: [v('V554 Camshaft', 5.5, 54, 9), v('V642 Piston', 6, 42, 8), v('V660 Carb', 6, 60, 10), v('V770 Big Block', 7, 70, 12)] },
  { brand: 'CAO', name: 'Brazilia', country: NIC, wrapper: 'Brazilian Arapiraca', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2001,
    flavor_notes: ['earth', 'cocoa', 'pepper', 'sweet spice'], description: 'Dark Brazilian wrapper over Nicaraguan filler. The Gol! is the one everyone knows.',
    vitolas: [v('Piranha', 4.5, 38, 6), v('Gol!', 5, 56, 8), v('Samba', 6.25, 54, 9), v('Amazon', 6, 60, 9)] },
  { brand: 'CAO', name: 'Italia', country: NIC, wrapper: 'Honduran Habano', binder: 'Honduran', filler: 'Italian, Nicaraguan, and Peruvian', strength: 'medium', year_introduced: 2005,
    flavor_notes: ['earth', 'nuts', 'cedar', 'spice'], description: 'A blend that includes Italian-grown tobacco. Earthy and medium-bodied.',
    vitolas: [v('Novella', 5.5, 46, 7), v('Ciao', 5, 56, 8), v('Gondola', 6.25, 54, 9)] },
  { brand: 'CAO', name: 'Gold', country: NIC, wrapper: 'Ecuadorian Connecticut', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'mild', year_introduced: 1996,
    flavor_notes: ['cream', 'cedar', 'nuts', 'honey'], description: 'CAO\'s mild Connecticut, smooth and dependable.',
    vitolas: [v('Corona', 5, 42, 6), v('Robusto', 5, 50, 7), v('Torpedo', 6.5, 52, 8), v('Churchill', 7, 48, 8)] },
  { brand: 'CAO', name: 'Mx2', country: NIC, wrapper: 'Connecticut Broadleaf Maduro', binder: 'Brazilian Maduro', filler: 'Nicaraguan, Peruvian, Honduran, and Dominican', strength: 'medium-full', year_introduced: 2004,
    flavor_notes: ['dark chocolate', 'coffee', 'earth', 'sweet spice'], description: 'Double maduro: broadleaf wrapper and a Brazilian maduro binder.',
    vitolas: [v('Robusto', 5, 52, 8), v('Toro', 6, 54, 9), v('Belicoso', 6.25, 52, 9)] },
  { brand: 'CAO', name: 'Pilon', country: NIC, wrapper: 'Ecuadorian Habano', binder: 'Nicaraguan', filler: 'Nicaraguan and Dominican', strength: 'medium-full', year_introduced: 2015,
    flavor_notes: ['earth', 'cocoa', 'pepper', 'cedar'], description: 'Fermented in traditional round pilones, which the blenders say yields a rounder flavor.',
    vitolas: [v('Robusto', 5, 52, 7), v('Toro', 6, 54, 8)] },

  // ── Altadis: Montecristo, Romeo y Julieta, H. Upmann ─────────────────────
  { brand: 'Montecristo', name: 'Classic', country: DR, wrapper: 'Connecticut Shade', binder: 'Dominican', filler: 'Dominican', strength: 'mild-medium', year_introduced: 2002,
    flavor_notes: ['cream', 'cedar', 'nuts', 'sweet tobacco'], description: 'The yellow-boxed Montecristo. Mild, elegant, and a gift-shop staple.',
    vitolas: [v('No. 3', 5.5, 44, 12), v('Robusto', 5, 50, 14), v('No. 2', 6.125, 52, 16), v('Toro', 6, 54, 16), v('Churchill', 7, 54, 17)] },
  { brand: 'Montecristo', name: 'White Series', country: DR, wrapper: 'Ecuadorian Connecticut', binder: 'Nicaraguan', filler: 'Dominican, Nicaraguan, and Peruvian', strength: 'mild-medium', year_introduced: 2004,
    flavor_notes: ['cream', 'cedar', 'toast', 'nuts'], description: 'A slightly richer Connecticut than the Classic. One of the best-selling cigars in the country.',
    vitolas: [v('Especial No. 3', 5.5, 44, 12), v('Rothchilde', 5, 52, 14), v('No. 2', 6.125, 52, 16), v('Toro', 6, 54, 16), v('Churchill', 7, 54, 17)] },
  { brand: 'Montecristo', name: 'Epic', country: DR, wrapper: 'Nicaraguan Habano', binder: 'Nicaraguan', filler: 'Dominican and Nicaraguan', strength: 'medium-full', year_introduced: 2012,
    flavor_notes: ['pepper', 'cedar', 'coffee', 'earth'], description: 'The fuller, Nicaraguan-leaning Montecristo built for the modern palate.',
    vitolas: [v('Robusto', 5.25, 52, 15), v('Toro', 6, 52, 16), v('Churchill', 7, 54, 18)] },
  { brand: 'Romeo y Julieta', name: '1875', country: DR, wrapper: 'Indonesian TBN', binder: 'Dominican', filler: 'Dominican', strength: 'mild-medium', year_introduced: 1995,
    flavor_notes: ['cedar', 'cream', 'sweet spice', 'nuts'], description: 'The classic Dominican Romeo with the red and gold band.',
    vitolas: [v('Cedro Deluxe No. 2', 5.5, 44, 7), v('Bully', 5, 50, 8), v('Churchill', 7, 50, 9)] },
  { brand: 'Romeo y Julieta', name: 'Reserva Real', country: DR, wrapper: 'Ecuadorian Connecticut', binder: 'Nicaraguan', filler: 'Dominican and Nicaraguan', strength: 'medium', year_introduced: 2002,
    flavor_notes: ['cedar', 'cream', 'pepper', 'nuts'], description: 'A step up from the 1875 in body, with a Connecticut wrapper and Nicaraguan filler.',
    vitolas: [v('Robusto', 5, 52, 9), v('Toro', 6, 54, 10), v('Churchill', 7, 54, 11)] },
  { brand: 'H. Upmann', name: '1844 Reserve', country: DR, wrapper: 'Ecuadorian Habano', binder: 'Nicaraguan', filler: 'Dominican and Nicaraguan', strength: 'medium', year_introduced: 2012,
    flavor_notes: ['cedar', 'earth', 'pepper', 'cream'], description: 'The modern H. Upmann, medium bodied with a habano wrapper.',
    vitolas: [v('Robusto', 5, 50, 8), v('Belicoso', 6.125, 52, 9), v('Toro', 6, 54, 9), v('Churchill', 7, 54, 10)] },

  // ── Rocky Patel ──────────────────────────────────────────────────────────
  { brand: 'Rocky Patel', name: 'Decade', country: HON, wrapper: 'Ecuadorian Sumatra', binder: 'Nicaraguan', filler: 'Nicaraguan and Dominican', strength: 'full', year_introduced: 2006,
    flavor_notes: ['pepper', 'cocoa', 'leather', 'cedar'], description: 'Made for the brand\'s tenth anniversary and still the flagship. Rich and full without harshness.',
    vitolas: [v('Robusto', 5, 50, 11), v('Lonsdale', 6.5, 44, 11), v('Toro', 6.5, 52, 12), v('Torpedo', 6.5, 52, 12), v('Emperor', 6, 60, 13)] },
  { brand: 'Rocky Patel', name: 'Vintage 1990', country: HON, wrapper: 'Honduran Broadleaf (aged)', binder: 'Nicaraguan', filler: 'Nicaraguan and Dominican', strength: 'medium', year_introduced: 2003,
    flavor_notes: ['cocoa', 'coffee', 'cedar', 'cream'], description: 'Built around broadleaf wrapper aged since 1990. Smooth and chocolatey.',
    vitolas: [v('Robusto', 5.5, 50, 10), v('Toro', 6.5, 52, 11), v('Torpedo', 6.5, 52, 11), v('Churchill', 7, 48, 11)] },
  { brand: 'Rocky Patel', name: 'Vintage 1992', country: HON, wrapper: 'Ecuadorian Sumatra (aged)', binder: 'Nicaraguan', filler: 'Nicaraguan and Dominican', strength: 'medium', year_introduced: 2003,
    flavor_notes: ['cedar', 'nuts', 'sweet spice', 'cream'], description: 'The lighter Vintage, with a Sumatra wrapper aged since 1992.',
    vitolas: [v('Robusto', 5.5, 50, 10), v('Toro', 6.5, 52, 11), v('Torpedo', 6.5, 52, 11), v('Churchill', 7, 48, 11)] },
  { brand: 'Rocky Patel', name: 'Sun Grown', country: HON, wrapper: 'Ecuadorian Sun Grown', binder: 'Nicaraguan', filler: 'Nicaraguan and Dominican', strength: 'medium-full', year_introduced: 2004,
    flavor_notes: ['pepper', 'cedar', 'earth', 'sweet tobacco'], description: 'A sun-grown Ecuadorian wrapper gives this one a spicy edge.',
    vitolas: [v('Robusto', 5.5, 50, 9), v('Toro', 6.5, 52, 10), v('Torpedo', 6.5, 52, 10), v('Sixty', 6, 60, 11)] },
  { brand: 'Rocky Patel', name: 'Sun Grown Maduro', country: HON, wrapper: 'Connecticut Broadleaf Maduro', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2015,
    flavor_notes: ['dark chocolate', 'espresso', 'pepper', 'earth'], description: 'Cigar Aficionado\'s number two cigar of 2016. Dark, sweet, and full.',
    vitolas: [v('Robusto', 5.5, 50, 10), v('Toro', 6.5, 52, 11), v('Torpedo', 6.5, 52, 11), v('Sixty', 6, 60, 12)] },
  { brand: 'Rocky Patel', name: 'The Edge Corojo', country: HON, wrapper: 'Honduran Corojo', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2004,
    flavor_notes: ['pepper', 'leather', 'earth', 'cedar'], description: 'Sold in cabinets of 100 with no cellophane. Strong, spicy, and a bargain.',
    vitolas: [v('Robusto', 5.5, 50, 7), v('Toro', 6, 52, 8), v('Torpedo', 6, 52, 8), v('Sixty', 6, 60, 9)] },
  { brand: 'Rocky Patel', name: 'The Edge Maduro', country: HON, wrapper: 'Costa Rican Maduro', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2004,
    flavor_notes: ['dark chocolate', 'pepper', 'earth', 'coffee'], description: 'The maduro version of the Edge, darker and sweeter.',
    vitolas: [v('Robusto', 5.5, 50, 7), v('Toro', 6, 52, 8), v('Torpedo', 6, 52, 8), v('Sixty', 6, 60, 9)] },
  { brand: 'Rocky Patel', name: 'Fifteenth Anniversary', country: HON, wrapper: 'Ecuadorian Habano', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2011,
    flavor_notes: ['pepper', 'cocoa', 'cedar', 'cream'], description: 'The anniversary blend that followed the Decade. Fuller and more refined.',
    vitolas: [v('Robusto', 5.5, 50, 12), v('Toro', 6.5, 52, 13), v('Torpedo', 6.5, 52, 13), v('Sixty', 6, 60, 14)] },

  // ── A.J. Fernandez ───────────────────────────────────────────────────────
  { brand: 'A.J. Fernandez', name: 'New World', country: NIC, wrapper: 'Nicaraguan Oscuro', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2014,
    flavor_notes: ['cocoa', 'pepper', 'earth', 'coffee'], description: 'Blended by A.J. and his father Ismael. A dark, affordable Nicaraguan puro.',
    vitolas: [v('Navegante', 5.5, 55, 8), v('Gobernador', 6.5, 55, 9)] },
  { brand: 'A.J. Fernandez', name: 'New World Cameroon', country: NIC, wrapper: 'Cameroon', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium', year_introduced: 2019,
    flavor_notes: ['sweet spice', 'cedar', 'nuts', 'cream'], description: 'The New World blend under a sweet Cameroon wrapper.',
    vitolas: [v('Robusto', 5.5, 50, 8), v('Toro', 6, 50, 9), v('Churchill', 7, 50, 10)] },
  { brand: 'A.J. Fernandez', name: 'New World Puro Especial', country: NIC, wrapper: 'Nicaraguan Habano', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2017,
    flavor_notes: ['pepper', 'cedar', 'earth', 'sweet spice'], description: 'A Nicaraguan puro from A.J.\'s own farms.',
    vitolas: [v('Robusto', 5.5, 52, 9), v('Toro', 6.5, 52, 10), v('Churchill', 7, 50, 11)] },
  { brand: 'A.J. Fernandez', name: 'Enclave', country: NIC, wrapper: 'Ecuadorian Habano', binder: 'Cameroon', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2015,
    flavor_notes: ['pepper', 'cocoa', 'cedar', 'nuts'], description: 'Cameroon binder under a habano wrapper. Spicy but balanced.',
    vitolas: [v('Robusto', 5, 52, 9), v('Toro', 6, 52, 10), v('Churchill', 7, 52, 11)] },
  { brand: 'A.J. Fernandez', name: 'Enclave Broadleaf', country: NIC, wrapper: 'Connecticut Broadleaf', binder: 'Cameroon', filler: 'Nicaraguan', strength: 'full', year_introduced: 2017,
    flavor_notes: ['dark chocolate', 'pepper', 'earth', 'coffee'], description: 'The Enclave with a broadleaf wrapper. Darker and fuller.',
    vitolas: [v('Robusto', 5, 52, 9), v('Toro', 6, 52, 10), v('Churchill', 7, 52, 11)] },
  { brand: 'A.J. Fernandez', name: 'San Lotano Oval', country: NIC, wrapper: 'Nicaraguan Habano', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2011,
    flavor_notes: ['pepper', 'cedar', 'cocoa', 'earth'], description: 'Pressed into an oval shape that sits well in the mouth. A well-loved Nicaraguan blend.',
    vitolas: [v('Robusto', 5, 55, 9), v('Toro', 6.5, 55, 10), v('Churchill', 7, 54, 11)] },
  { brand: 'A.J. Fernandez', name: 'San Lotano Requiem', country: NIC, wrapper: 'Nicaraguan Habano', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2016,
    flavor_notes: ['pepper', 'espresso', 'earth', 'leather'], description: 'The strongest San Lotano.',
    vitolas: [v('Robusto', 5.5, 54, 9), v('Toro', 6.5, 54, 10), v('Churchill', 7, 54, 11)] },
  { brand: 'A.J. Fernandez', name: 'Bellas Artes', country: NIC, wrapper: 'Nicaraguan Rojita (hybrid)', binder: 'Nicaraguan', filler: 'Nicaraguan, Honduran, and Brazilian', strength: 'medium', year_introduced: 2016,
    flavor_notes: ['cedar', 'sweet spice', 'cream', 'coffee'], description: 'Wrapped in a hybrid leaf A.J. developed on his farm. Smooth and medium.',
    vitolas: [v('Robusto', 5.5, 52, 9), v('Short Churchill', 6, 48, 10), v('Toro', 6, 54, 10), v('Gordo', 6, 60, 11)] },
  { brand: 'A.J. Fernandez', name: 'Bellas Artes Maduro', country: NIC, wrapper: 'Mexican San Andrés Maduro', binder: 'Nicaraguan', filler: 'Nicaraguan, Honduran, and Brazilian', strength: 'medium-full', year_introduced: 2018,
    flavor_notes: ['dark chocolate', 'coffee', 'earth', 'sweet spice'], description: 'The Bellas Artes blend with a San Andrés maduro wrapper.',
    vitolas: [v('Robusto', 5.5, 52, 9), v('Short Churchill', 6, 48, 10), v('Toro', 6, 54, 10), v('Gordo', 6, 60, 11)] },
  { brand: 'A.J. Fernandez', name: 'Días de Gloria', country: NIC, wrapper: 'Nicaraguan Habano', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2020,
    flavor_notes: ['pepper', 'cocoa', 'earth', 'cedar'], description: 'A tribute to A.J.\'s grandfather. Nicaraguan puro, box pressed, full.',
    vitolas: [v('Robusto', 5.5, 52, 10), v('Toro', 6.5, 52, 11), v('Churchill', 7, 50, 12)] },

  // ── Perdomo ──────────────────────────────────────────────────────────────
  { brand: 'Perdomo', name: '20th Anniversary Sun Grown', country: NIC, wrapper: 'Nicaraguan Sun Grown', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2012,
    flavor_notes: ['pepper', 'cedar', 'cocoa', 'cream'], description: 'Bourbon-barrel-aged wrapper over a six-year-aged blend. Available in Sun Grown, Maduro, and Connecticut.',
    vitolas: [v('Robusto', 5, 56, 10), v('Epicure', 6, 56, 11), v('Torpedo', 6.5, 54, 11), v('Churchill', 7, 56, 12)] },
  { brand: 'Perdomo', name: '20th Anniversary Maduro', country: NIC, wrapper: 'Nicaraguan Maduro', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2012,
    flavor_notes: ['dark chocolate', 'coffee', 'earth', 'sweet spice'], description: 'The maduro version of the 20th Anniversary.',
    vitolas: [v('Robusto', 5, 56, 10), v('Epicure', 6, 56, 11), v('Torpedo', 6.5, 54, 11), v('Churchill', 7, 56, 12)] },
  { brand: 'Perdomo', name: 'Habano Bourbon Barrel-Aged Sun Grown', country: NIC, wrapper: 'Nicaraguan Sun Grown (bourbon barrel aged)', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2015,
    flavor_notes: ['oak', 'sweet spice', 'cedar', 'cocoa'], description: 'Wrapper aged in bourbon barrels. Also sold as Maduro and Connecticut.',
    vitolas: [v('Robusto', 5, 54, 9), v('Epicure', 6, 56, 10), v('Torpedo', 6.5, 54, 10), v('Gordo', 6, 60, 11)] },
  { brand: 'Perdomo', name: 'Habano Bourbon Barrel-Aged Maduro', country: NIC, wrapper: 'Nicaraguan Maduro (bourbon barrel aged)', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2015,
    flavor_notes: ['dark chocolate', 'oak', 'coffee', 'sweet spice'], description: 'The maduro Bourbon Barrel-Aged.',
    vitolas: [v('Robusto', 5, 54, 9), v('Epicure', 6, 56, 10), v('Torpedo', 6.5, 54, 10), v('Gordo', 6, 60, 11)] },
  { brand: 'Perdomo', name: 'Lot 23', country: NIC, wrapper: 'Nicaraguan (natural, maduro, or Connecticut)', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium', year_introduced: 2005,
    flavor_notes: ['cedar', 'coffee', 'earth', 'cream'], description: 'Named for the farm lot the tobacco comes from. A reliable everyday Nicaraguan.',
    vitolas: [v('Robusto', 5, 50, 7), v('Toro', 6, 50, 8), v('Belicoso', 6, 54, 8), v('Churchill', 7, 50, 8)] },
  { brand: 'Perdomo', name: 'Reserve 10th Anniversary Champagne', country: NIC, wrapper: 'Ecuadorian Connecticut', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'mild-medium', year_introduced: 2008,
    flavor_notes: ['cream', 'cedar', 'nuts', 'honey'], description: 'A creamy Connecticut over aged Nicaraguan filler. Perdomo\'s best-selling line.',
    vitolas: [v('Robusto', 5, 54, 9), v('Epicure', 6, 54, 10), v('Torpedo', 6.5, 54, 10), v('Churchill', 7, 54, 11)] },

  // ── Alec Bradley ─────────────────────────────────────────────────────────
  { brand: 'Alec Bradley', name: 'Prensado', country: HON, wrapper: 'Honduran Corojo (Trojes)', binder: 'Nicaraguan', filler: 'Honduran and Nicaraguan', strength: 'full', year_introduced: 2008,
    flavor_notes: ['pepper', 'cocoa', 'leather', 'cedar'], description: 'Box-pressed with a Trojes corojo wrapper. Cigar of the Year in 2011.',
    vitolas: [v('Corona Gorda', 5.625, 46, 10), v('Robusto', 5, 50, 11), v('Torpedo', 6.125, 52, 12), v('Toro', 6, 52, 12), v('Gran Toro', 6, 54, 13), v('Churchill', 7, 48, 13)] },
  { brand: 'Alec Bradley', name: 'Black Market', country: HON, wrapper: 'Nicaraguan Jalapa', binder: 'Sumatra', filler: 'Honduran and Panamanian', strength: 'medium-full', year_introduced: 2011,
    flavor_notes: ['cocoa', 'pepper', 'earth', 'sweet spice'], description: 'Dark, sweet, and medium-full. One of Alec Bradley\'s best sellers.',
    vitolas: [v('Robusto', 5.25, 52, 9), v('Toro', 6, 50, 10), v('Torpedo', 6.125, 52, 10), v('Churchill', 7, 50, 10), v('Gordo', 6, 60, 11)] },
  { brand: 'Alec Bradley', name: 'American Classic Blend', country: HON, wrapper: 'Ecuadorian Connecticut', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'mild-medium', year_introduced: 2011,
    flavor_notes: ['cream', 'cedar', 'nuts', 'toast'], description: 'A smooth, affordable Connecticut.',
    vitolas: [v('Robusto', 5, 50, 6), v('Toro', 6, 50, 7), v('Churchill', 7, 50, 7), v('Gordo', 6, 60, 8)] },
  { brand: 'Alec Bradley', name: 'Magic Toast', country: HON, wrapper: 'Honduran (Trojes)', binder: 'Nicaraguan', filler: 'Honduran and Nicaraguan', strength: 'medium-full', year_introduced: 2018,
    flavor_notes: ['toast', 'cocoa', 'pepper', 'cedar'], description: 'Named for the toast the founders raised when they found the wrapper.',
    vitolas: [v('Robusto', 5.5, 52, 10), v('Toro', 6, 52, 11), v('Gordo', 6, 60, 12)] },

  // ── Camacho ──────────────────────────────────────────────────────────────
  { brand: 'Camacho', name: 'Corojo', country: HON, wrapper: 'Honduran Corojo', binder: 'Honduran', filler: 'Honduran and Dominican', strength: 'full', year_introduced: 2000,
    flavor_notes: ['pepper', 'earth', 'cedar', 'leather'], description: 'Authentic corojo grown in Honduras. Bold and unapologetic.',
    vitolas: [v('Robusto', 5, 50, 8), v('Toro', 6, 50, 9), v('Churchill', 7, 48, 9), v('Gigante', 6, 60, 10)] },
  { brand: 'Camacho', name: 'Connecticut', country: HON, wrapper: 'Ecuadorian Connecticut', binder: 'Honduran', filler: 'Honduran and Dominican', strength: 'mild-medium', year_introduced: 2005,
    flavor_notes: ['cream', 'cedar', 'nuts', 'pepper'], description: 'The bold brand\'s mild option, still with a little Camacho kick.',
    vitolas: [v('Robusto', 5, 50, 8), v('Toro', 6, 50, 9), v('Churchill', 7, 48, 9), v('Gigante', 6, 60, 10)] },
  { brand: 'Camacho', name: 'Triple Maduro', country: HON, wrapper: 'Mexican San Andrés Maduro', binder: 'Honduran Maduro', filler: 'Honduran, Dominican, and Brazilian Maduro', strength: 'full', year_introduced: 2007,
    flavor_notes: ['dark chocolate', 'espresso', 'earth', 'pepper'], description: 'Maduro wrapper, binder, and filler. Dark all the way through.',
    vitolas: [v('Robusto', 5, 50, 10), v('Toro', 6, 50, 11), v('Gigante', 6, 60, 12)] },
  { brand: 'Camacho', name: 'Ecuador', country: HON, wrapper: 'Ecuadorian Habano', binder: 'Brazilian', filler: 'Honduran and Dominican', strength: 'medium-full', year_introduced: 2013,
    flavor_notes: ['pepper', 'cocoa', 'cedar', 'nuts'], description: 'A habano-wrapped Camacho with a rounder profile than the Corojo.',
    vitolas: [v('Robusto', 5, 50, 8), v('Toro', 6, 50, 9), v('Churchill', 7, 48, 9), v('Gigante', 6, 60, 10)] },

  // ── Joya de Nicaragua ────────────────────────────────────────────────────
  { brand: 'Joya de Nicaragua', name: 'Antaño 1970', country: NIC, wrapper: 'Nicaraguan Habano', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2001,
    flavor_notes: ['pepper', 'earth', 'leather', 'cocoa'], description: 'The cigar that defined Nicaraguan strength. Not for beginners.',
    vitolas: [v('Machito', 4.75, 42, 7), v('Consul', 4.5, 52, 8), v('Robusto Grande', 5.5, 52, 9), v('Gran Consul', 4.75, 60, 9), v('Belicoso', 6, 54, 10), v('Churchill', 6.875, 48, 10), v('Lancero', 7, 38, 9)] },
  { brand: 'Joya de Nicaragua', name: 'Antaño Dark Corojo', country: NIC, wrapper: 'Nicaraguan Corojo Oscuro', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2010,
    flavor_notes: ['dark chocolate', 'pepper', 'earth', 'espresso'], description: 'The Antaño with a darker corojo wrapper. Rich and strong.',
    vitolas: [v('Azarosa', 4.5, 54, 9), v('Poderoso', 6, 54, 10)] },
  { brand: 'Joya de Nicaragua', name: 'Joya Black', country: NIC, wrapper: 'Mexican San Andrés Maduro', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2015,
    flavor_notes: ['cocoa', 'coffee', 'earth', 'sweet spice'], description: 'A modern, medium-full Joya with a San Andrés wrapper.',
    vitolas: [v('Robusto', 5, 50, 7), v('Nocturno', 6.5, 46, 8), v('Toro', 6, 52, 8), v('Doble Robusto', 5, 56, 8)] },
  { brand: 'Joya de Nicaragua', name: 'Joya Red', country: NIC, wrapper: 'Nicaraguan Habano', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium', year_introduced: 2014,
    flavor_notes: ['cedar', 'sweet spice', 'coffee', 'cream'], description: 'The approachable Joya, medium bodied and well priced.',
    vitolas: [v('Short Churchill', 4.75, 48, 6), v('Robusto', 5.25, 50, 7), v('Toro', 6, 52, 7), v('Cañonazo', 5.5, 54, 8)] },
  { brand: 'Joya de Nicaragua', name: 'Clásico', country: NIC, wrapper: 'Ecuadorian Connecticut', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'mild-medium', year_introduced: 1968,
    flavor_notes: ['cream', 'cedar', 'nuts', 'mild spice'], description: 'The original Joya, once served at the White House. Mild for a Nicaraguan.',
    vitolas: [v('Consul', 4.5, 52, 6), v('Toro', 6, 50, 7), v('Churchill', 6.875, 48, 7)] },

  // ── Crowned Heads ────────────────────────────────────────────────────────
  { brand: 'Crowned Heads', name: 'Four Kicks', country: DR, wrapper: 'Ecuadorian Habano', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium', year_introduced: 2011,
    flavor_notes: ['cedar', 'nuts', 'sweet spice', 'cream'], description: 'Crowned Heads\' debut, made at E.P. Carrillo\'s factory. Balanced and medium.',
    vitolas: [v('Seleccion No. 5', 5.5, 44, 8), v('Robusto', 5, 50, 9), v('Corona Gorda', 5.625, 46, 9), v('Piramide', 6.125, 52, 10), v('Sublime', 6, 54, 10)] },
  { brand: 'Crowned Heads', name: 'Four Kicks Maduro', country: DR, wrapper: 'Connecticut Broadleaf', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2019,
    flavor_notes: ['cocoa', 'coffee', 'earth', 'sweet spice'], description: 'The Four Kicks blend under a broadleaf wrapper.',
    vitolas: [v('Robusto', 5, 50, 10), v('Corona Gorda', 5.625, 46, 10), v('Sublime', 6, 54, 11)] },
  { brand: 'Crowned Heads', name: 'Headley Grange', country: NIC, wrapper: 'Ecuadorian Sumatra', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2012,
    flavor_notes: ['pepper', 'cedar', 'cocoa', 'earth'], description: 'Made by My Father and named after the studio where Led Zeppelin recorded.',
    vitolas: [v('Eminentes', 5.375, 46, 9), v('Hermoso No. 4', 5, 48, 10)] },
  { brand: 'Crowned Heads', name: 'Jericho Hill', country: NIC, wrapper: 'Mexican San Andrés', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2014,
    flavor_notes: ['dark chocolate', 'pepper', 'earth', 'coffee'], description: 'A Johnny Cash tribute made by My Father. Full bodied and dark.',
    vitolas: [v('.44S', 5, 44, 9)] },
  { brand: 'Crowned Heads', name: 'Mil Días', country: NIC, wrapper: 'Ecuadorian Habano', binder: 'Nicaraguan', filler: 'Nicaraguan, Peruvian, and Costa Rican', strength: 'medium-full', year_introduced: 2020,
    flavor_notes: ['cedar', 'sweet spice', 'coffee', 'cream'], description: 'Named for the thousand days it took to blend. Made at Tabacalera Pichardo.',
    vitolas: [v('Edmundo', 5.5, 52, 11), v('Sublime', 6, 54, 12)] },

  // ── Tatuaje ──────────────────────────────────────────────────────────────
  { brand: 'Tatuaje', name: 'Havana VI', country: NIC, wrapper: 'Nicaraguan Corojo 99', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium', year_introduced: 2005,
    flavor_notes: ['cedar', 'pepper', 'cream', 'nuts'], description: 'The red-label Tatuaje, made by My Father. Cuban style at a fair price.',
    vitolas: [v('Angeles', 4.625, 42, 8), v('Nobles', 5, 50, 9), v('Hermosos', 5.625, 46, 9), v('Artistas', 6.125, 52, 10)] },
  { brand: 'Tatuaje', name: 'Miami (Brown Label)', country: NIC, wrapper: 'Nicaraguan Corojo 99', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2003,
    flavor_notes: ['pepper', 'cedar', 'earth', 'cocoa'], description: 'Pete Johnson\'s original line, rolled by Don Pepin Garcia. Full and Cuban in spirit.',
    vitolas: [v('Noellas', 5.125, 42, 11), v('Regios', 5.5, 50, 13), v('Cojonu 2003', 6.5, 52, 15), v('Especiales', 7.5, 38, 13), v('Tainos', 7.625, 49, 16)] },

  // ── Foundation ───────────────────────────────────────────────────────────
  { brand: 'Foundation', name: 'The Tabernacle', country: NIC, wrapper: 'Connecticut Broadleaf', binder: 'Mexican San Andrés', filler: 'Nicaraguan and Honduran', strength: 'full', year_introduced: 2016,
    flavor_notes: ['dark chocolate', 'pepper', 'earth', 'espresso'], description: 'Nick Melillo\'s broadleaf showcase. Dark, dense, and full.',
    vitolas: [v('Robusto', 5, 50, 12), v('Toro', 6, 52, 13), v('Double Corona', 7, 50, 14), v('Lancero', 7, 40, 13)] },
  { brand: 'Foundation', name: 'El Güegüense', country: NIC, wrapper: 'Nicaraguan Corojo 99', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2015,
    flavor_notes: ['cedar', 'pepper', 'cream', 'sweet spice'], description: 'Foundation\'s first blend, a Nicaraguan puro named after a folk play.',
    vitolas: [v('Corona Gorda', 5.625, 46, 11), v('Robusto', 5.5, 50, 12), v('Toro', 6, 54, 13), v('Churchill', 7, 48, 14)] },
  { brand: 'Foundation', name: 'Charter Oak Connecticut Shade', country: NIC, wrapper: 'Connecticut Shade', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'mild', year_introduced: 2016,
    flavor_notes: ['cream', 'cedar', 'nuts', 'toast'], description: 'An affordable, mild Connecticut-wrapped everyday cigar.',
    vitolas: [v('Rothschild', 4.5, 50, 6), v('Toro', 6, 52, 7), v('Grande', 6, 60, 8)] },
  { brand: 'Foundation', name: 'Charter Oak Broadleaf', country: NIC, wrapper: 'Connecticut Broadleaf', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium', year_introduced: 2016,
    flavor_notes: ['cocoa', 'earth', 'coffee', 'sweet spice'], description: 'The broadleaf Charter Oak, a bit more body for the same price.',
    vitolas: [v('Rothschild', 4.5, 50, 6), v('Toro', 6, 52, 7), v('Grande', 6, 60, 8)] },

  // ── Warped, Dunbarton, RoMa Craft, Illusione ─────────────────────────────
  { brand: 'Warped', name: 'Flor del Valle', country: NIC, wrapper: 'Nicaraguan Corojo 99', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium', year_introduced: 2015,
    flavor_notes: ['cedar', 'cream', 'floral', 'pepper'], description: 'Made at Aganorsa. Refined, Cuban-styled, and medium bodied.',
    vitolas: [v('Las Brumas', 5.5, 50, 11), v('Gran Valle', 6, 54, 12)] },
  { brand: 'Warped', name: 'La Colmena', country: NIC, wrapper: 'Ecuadorian Deflorada', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium', year_introduced: 2014,
    flavor_notes: ['cream', 'cedar', 'nuts', 'honey'], description: 'One of the most elegant cigars from Aganorsa, with a rare deflorada wrapper.',
    vitolas: [v('Amado No. 44', 5.5, 44, 13)] },
  { brand: 'Warped', name: 'Serie Gran Reserva 1988', country: NIC, wrapper: 'Nicaraguan Corojo', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium', year_introduced: 2016,
    flavor_notes: ['cedar', 'sweet spice', 'cream', 'earth'], description: 'Warped\'s tribute to the year its founder was born.',
    vitolas: [v('Corona Gorda', 5.625, 46, 11)] },
  { brand: 'Dunbarton Tobacco & Trust', name: 'Sobremesa', country: NIC, wrapper: 'Ecuadorian Habano Rosado', binder: 'Mexican San Andrés', filler: 'Nicaraguan and Pennsylvania Broadleaf', strength: 'medium-full', year_introduced: 2015,
    flavor_notes: ['cedar', 'baking spice', 'cocoa', 'cream'], description: 'Steve Saka\'s first blend after Liga Privada. Layered and refined.',
    vitolas: [v('Corona Grande', 5.25, 44, 11), v('Robusto Largo', 5.25, 52, 12), v('Cervantes Fino', 6.25, 46, 12), v('El Americano', 6, 52, 13), v('Gran Imperiales', 7, 54, 14)] },
  { brand: 'Dunbarton Tobacco & Trust', name: 'Sobremesa Brûlée', country: NIC, wrapper: 'Ecuadorian Connecticut', binder: 'Mexican San Andrés', filler: 'Nicaraguan', strength: 'mild-medium', year_introduced: 2019,
    flavor_notes: ['cream', 'caramel', 'cedar', 'nuts'], description: 'A sweet, creamy Connecticut that surprised people who expected Saka to only make full-bodied cigars.',
    vitolas: [v('Robusto', 5.25, 52, 12), v('Toro', 6, 52, 13), v('Gordo', 6, 60, 14)] },
  { brand: 'Dunbarton Tobacco & Trust', name: 'Mi Querida', country: NIC, wrapper: 'Connecticut Broadleaf', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2016,
    flavor_notes: ['dark chocolate', 'earth', 'pepper', 'coffee'], description: 'Saka\'s return to broadleaf. Dark, sweet, and strong.',
    vitolas: [v('Ancho Corta', 5, 54, 10), v('Muy Ancho', 6, 60, 12)] },
  { brand: 'Dunbarton Tobacco & Trust', name: 'Umbagog', country: NIC, wrapper: 'Connecticut Broadleaf', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2017,
    flavor_notes: ['earth', 'cocoa', 'pepper', 'wood'], description: 'Broadleaf that did not make the Mi Querida grade, sold at a working-man\'s price. Rustic and great.',
    vitolas: [v('Robusto Plus', 5.25, 52, 7), v('Toro Toro', 6, 52, 8), v('Gordo Gordo', 6, 56, 8)] },
  { brand: 'RoMa Craft', name: 'CroMagnon', country: NIC, wrapper: 'Connecticut Broadleaf', binder: 'Cameroon', filler: 'Nicaraguan', strength: 'full', year_introduced: 2011,
    flavor_notes: ['earth', 'pepper', 'dark chocolate', 'leather'], description: 'Broadleaf over a Cameroon binder. Dense, full, and named after prehistoric skulls.',
    vitolas: [v('Knuckle Dragger', 4, 52, 8), v('Mode 5', 5, 50, 9), v('EMH', 5, 56, 10), v('Anthropology', 5.75, 46, 9), v('Cranium', 6, 54, 10), v('Atlatl', 7, 38, 9)] },
  { brand: 'RoMa Craft', name: 'Aquitaine', country: NIC, wrapper: 'Ecuadorian Habano Ligero', binder: 'Cameroon', filler: 'Nicaraguan', strength: 'full', year_introduced: 2012,
    flavor_notes: ['pepper', 'cedar', 'earth', 'sweet spice'], description: 'The CroMagnon blend under a habano ligero wrapper. Spicier and brighter.',
    vitolas: [v('Knuckle Dragger', 4, 52, 8), v('Mode 5', 5, 50, 9), v('EMH', 5, 56, 10), v('Anthropology', 5.75, 46, 9), v('Cranium', 6, 54, 10), v('Atlatl', 7, 38, 9)] },
  { brand: 'RoMa Craft', name: 'Neanderthal', country: NIC, wrapper: 'Mexican San Andrés', binder: 'Connecticut Broadleaf', filler: 'Nicaraguan, Dominican, and Pennsylvania Ligero', strength: 'full', year_introduced: 2014,
    flavor_notes: ['pepper', 'earth', 'dark chocolate', 'leather'], description: 'RoMa Craft\'s strongest cigar, with Pennsylvania ligero in the blend.',
    vitolas: [v('OM', 4, 46, 9), v('SGP', 4.125, 54, 10), v('HN', 5, 52, 11), v('HoxD', 5.75, 56, 13), v('KFG', 5.5, 58, 13)] },
  { brand: 'Illusione', name: 'Original Documents', country: NIC, wrapper: 'Nicaraguan Corojo', binder: 'Nicaraguan', filler: 'Nicaraguan (Criollo and Corojo)', strength: 'medium-full', year_introduced: 2006,
    flavor_notes: ['cedar', 'pepper', 'cream', 'earth'], description: 'Dion Giolito\'s first line, using first-generation Cuban-seed tobacco from Aganorsa.',
    vitolas: [v('68 Bombone', 4, 44, 8), v('88', 5, 52, 10), v('cg:4', 5.625, 48, 10), v('888', 6.75, 48, 11)] },
  { brand: 'Illusione', name: 'Rothchildes', country: NIC, wrapper: 'Mexican San Andrés', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium', year_introduced: 2013,
    flavor_notes: ['cocoa', 'earth', 'coffee', 'sweet spice'], description: 'A short, affordable San Andrés smoke that punches above its price.',
    vitolas: [v('Rothchildes', 4.5, 50, 6)] },

  // ── E.P. Carrillo, Aging Room, Espinosa, Southern Draw, Plasencia ─────────
  { brand: 'E.P. Carrillo', name: 'Encore', country: DR, wrapper: 'Nicaraguan Habano', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2018,
    flavor_notes: ['cedar', 'sweet spice', 'cocoa', 'cream'], description: 'A Nicaraguan puro from a Dominican factory. Cigar of the Year in 2018.',
    vitolas: [v('Majestic', 5.375, 52, 12), v('Celestial', 6.25, 54, 13)] },
  { brand: 'E.P. Carrillo', name: 'Pledge', country: DR, wrapper: 'Connecticut Habano', binder: 'Ecuadorian', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2020,
    flavor_notes: ['cocoa', 'earth', 'pepper', 'sweet spice'], description: 'Cigar of the Year in 2020. A dark Connecticut-grown habano wrapper.',
    vitolas: [v('Prequel', 5, 50, 12), v('Apogee', 6, 52, 13)] },
  { brand: 'E.P. Carrillo', name: 'La Historia', country: DR, wrapper: 'Mexican San Andrés', binder: 'Ecuadorian Sumatra', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2014,
    flavor_notes: ['dark chocolate', 'coffee', 'earth', 'sweet spice'], description: 'Named after the Carrillo family history. The E-III was number two cigar of 2014.',
    vitolas: [v('Regalias d\'Celia', 5.375, 52, 11), v('Doña Elena', 6.125, 50, 12), v('E-III', 6.875, 54, 13)] },
  { brand: 'E.P. Carrillo', name: 'Inch Natural', country: DR, wrapper: 'Ecuadorian Sumatra', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2012,
    flavor_notes: ['cedar', 'earth', 'pepper', 'nuts'], description: 'Big ring gauges measured in fractions of an inch.',
    vitolas: [v('No. 62', 5, 62, 11), v('No. 64', 6.125, 64, 12)] },
  { brand: 'Aging Room', name: 'Quattro Nicaragua', country: NIC, wrapper: 'Nicaraguan Habano', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2019,
    flavor_notes: ['cedar', 'sweet spice', 'cocoa', 'cream'], description: 'Box-pressed by A.J. Fernandez for Rafael Nodal. Cigar of the Year in 2019.',
    vitolas: [v('Espressivo', 5, 50, 11), v('Maestro', 6, 52, 12), v('Concerto', 7, 50, 13)] },
  { brand: 'Espinosa', name: 'Laranja Reserva', country: NIC, wrapper: 'Brazilian Laranja', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2014,
    flavor_notes: ['citrus', 'cedar', 'sweet spice', 'cream'], description: 'An orange-tinted Brazilian wrapper with a bright, citrusy edge.',
    vitolas: [v('Corona Gorda', 6, 46, 9), v('Robusto Extra', 5.5, 54, 10), v('Toro', 6, 52, 10)] },
  { brand: 'Espinosa', name: '601 La Bomba', country: NIC, wrapper: 'Nicaraguan Habano', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2010,
    flavor_notes: ['pepper', 'earth', 'leather', 'espresso'], description: 'Ligero heavy and full strength, with a fuse-like pigtail cap.',
    vitolas: [v('Atomic', 5, 52, 8), v('Napalm', 5.5, 50, 8), v('Nuclear', 6, 54, 9)] },
  { brand: 'Espinosa', name: '601 Blue Label Maduro', country: NIC, wrapper: 'Connecticut Broadleaf Maduro', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2006,
    flavor_notes: ['dark chocolate', 'coffee', 'earth', 'sweet spice'], description: 'Box-pressed broadleaf. The 601 Blue has been a maduro benchmark for years.',
    vitolas: [v('Robusto', 5, 52, 8), v('Toro', 6, 52, 9)] },
  { brand: 'Espinosa', name: 'Crema', country: NIC, wrapper: 'Ecuadorian Connecticut', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'mild-medium', year_introduced: 2016,
    flavor_notes: ['cream', 'cedar', 'nuts', 'honey'], description: 'Espinosa\'s Connecticut. Creamy with a little Nicaraguan backbone.',
    vitolas: [v('Robusto', 5, 52, 8), v('Toro', 6, 52, 9)] },
  { brand: 'Southern Draw', name: 'Jacobs Ladder', country: NIC, wrapper: 'Pennsylvania Broadleaf', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2017,
    flavor_notes: ['dark chocolate', 'pepper', 'earth', 'coffee'], description: 'Made by A.J. Fernandez for a veteran-owned brand. Full strength.',
    vitolas: [v('Robusto', 5.5, 54, 10), v('Toro', 6, 52, 11)] },
  { brand: 'Southern Draw', name: 'Kudzu', country: NIC, wrapper: 'Ecuadorian Habano Oscuro', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2016,
    flavor_notes: ['pepper', 'cocoa', 'cedar', 'earth'], description: 'The brand\'s first release, a dark habano oscuro.',
    vitolas: [v('Robusto', 5.5, 54, 9), v('Toro', 6, 52, 10)] },
  { brand: 'Southern Draw', name: 'Rose of Sharon', country: NIC, wrapper: 'Ecuadorian Connecticut', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'mild-medium', year_introduced: 2017,
    flavor_notes: ['cream', 'cedar', 'nuts', 'honey'], description: 'A creamy Connecticut named for the founder\'s wife.',
    vitolas: [v('Robusto', 5.5, 54, 9), v('Toro', 6, 52, 10)] },
  { brand: 'Plasencia', name: 'Alma Fuerte', country: NIC, wrapper: 'Nicaraguan (sun grown)', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'full', year_introduced: 2016,
    flavor_notes: ['pepper', 'cocoa', 'cedar', 'earth'], description: 'The strongest of Plasencia\'s Alma series, made with the family\'s oldest tobaccos.',
    vitolas: [v('Generacion V', 5, 54, 20), v('Nestor IV', 6.25, 54, 21)] },

  // ── La Flor Dominicana, Avo, Kristoff, Gurkha, Baccarat, Diamond Crown, Brick House, Casa Magna ─
  { brand: 'La Flor Dominicana', name: 'Double Ligero', country: DR, wrapper: 'Ecuadorian Sun Grown', binder: 'Dominican', filler: 'Dominican (double ligero)', strength: 'full', year_introduced: 2001,
    flavor_notes: ['pepper', 'leather', 'earth', 'cedar'], description: 'Two ligero leaves in every filler. One of the strongest regular-production cigars anywhere.',
    vitolas: [v('Chisel', 6, 54, 12), v('DL-654', 6, 54, 12), v('DL-700', 6, 60, 13)] },
  { brand: 'La Flor Dominicana', name: 'Ligero', country: DR, wrapper: 'Ecuadorian Sun Grown', binder: 'Dominican', filler: 'Dominican (ligero)', strength: 'medium-full', year_introduced: 1999,
    flavor_notes: ['pepper', 'cedar', 'earth', 'nuts'], description: 'The single-ligero LFD, strong but a step below the Double Ligero.',
    vitolas: [v('L-500', 5, 50, 10)] },
  { brand: 'La Flor Dominicana', name: 'Andalusian Bull', country: DR, wrapper: 'Ecuadorian Habano', binder: 'Dominican', filler: 'Dominican', strength: 'full', year_introduced: 2016,
    flavor_notes: ['pepper', 'cocoa', 'cedar', 'sweet spice'], description: 'A huge figurado that was Cigar of the Year in 2016.',
    vitolas: [v('Andalusian Bull', 6.5, 64, 15)] },
  { brand: 'La Flor Dominicana', name: 'Air Bender', country: DR, wrapper: 'Ecuadorian Habano', binder: 'Dominican', filler: 'Dominican', strength: 'full', year_introduced: 2010,
    flavor_notes: ['pepper', 'earth', 'leather', 'cocoa'], description: 'A full-bodied LFD in the brand\'s signature Chisel shape and classic sizes.',
    vitolas: [v('Matatan', 5, 50, 10), v('Chisel', 6, 54, 12)] },
  { brand: 'Avo', name: 'Classic', country: DR, wrapper: 'Ecuadorian Connecticut', binder: 'Dominican', filler: 'Dominican', strength: 'mild-medium', year_introduced: 1988,
    flavor_notes: ['cream', 'cedar', 'nuts', 'honey'], description: 'Avo Uvezian\'s original, made by Davidoff. Mild and polished.',
    vitolas: [v('No. 9', 4.75, 48, 12), v('Robusto', 5, 50, 13), v('No. 2', 6, 50, 15), v('Piramide', 7, 54, 18)] },
  { brand: 'Avo', name: 'Syncro Nicaragua', country: DR, wrapper: 'Ecuadorian Habano', binder: 'Mexican', filler: 'Dominican, Nicaraguan, and Peruvian', strength: 'medium', year_introduced: 2014,
    flavor_notes: ['pepper', 'cedar', 'cream', 'nuts'], description: 'Avo\'s first blend to lean on Nicaraguan tobacco.',
    vitolas: [v('Short Robusto', 4, 52, 11), v('Robusto', 5, 50, 13), v('Toro', 6, 54, 15)] },
  { brand: 'Kristoff', name: 'Corojo Limitada', country: DR, wrapper: 'Honduran Corojo', binder: 'Dominican', filler: 'Dominican and Nicaraguan', strength: 'medium-full', year_introduced: 2005,
    flavor_notes: ['pepper', 'cocoa', 'cedar', 'earth'], description: 'Pigtail cap and closed foot. Kristoff\'s best-known blend.',
    vitolas: [v('Robusto', 5.5, 54, 9), v('Torpedo', 6.125, 52, 10), v('Churchill', 7, 50, 10)] },
  { brand: 'Kristoff', name: 'Maduro', country: DR, wrapper: 'Brazilian Maduro', binder: 'Dominican', filler: 'Dominican and Nicaraguan', strength: 'medium-full', year_introduced: 2005,
    flavor_notes: ['dark chocolate', 'coffee', 'earth', 'sweet spice'], description: 'The Kristoff maduro with a Brazilian wrapper.',
    vitolas: [v('Robusto', 5.5, 54, 9), v('Torpedo', 6.125, 52, 10), v('Churchill', 7, 50, 10), v('Matador', 6.5, 56, 11)] },
  { brand: 'Kristoff', name: 'Sumatra', country: DR, wrapper: 'Ecuadorian Sumatra', binder: 'Dominican', filler: 'Dominican and Nicaraguan', strength: 'medium', year_introduced: 2007,
    flavor_notes: ['cedar', 'sweet spice', 'nuts', 'cream'], description: 'A medium-bodied Sumatra-wrapped Kristoff.',
    vitolas: [v('Robusto', 5.5, 54, 9), v('Torpedo', 6.125, 52, 10), v('Churchill', 7, 50, 10)] },
  { brand: 'Gurkha', name: 'Cellar Reserve 15 Year', country: DR, wrapper: 'Dominican Olor', binder: 'Dominican', filler: 'Dominican (15-year-aged)', strength: 'medium', year_introduced: 2011,
    flavor_notes: ['cedar', 'cream', 'sweet spice', 'nuts'], description: 'Gurkha\'s best-reviewed regular line, with 15-year-aged Dominican filler.',
    vitolas: [v('Grand Rothchild', 6, 54, 12), v('Solara', 5.5, 58, 12), v('Hedonism', 6, 58, 13)] },
  { brand: 'Gurkha', name: 'Royal Challenge', country: DR, wrapper: 'Ecuadorian Habano', binder: 'Honduran', filler: 'Dominican and Nicaraguan', strength: 'medium', year_introduced: 2009,
    flavor_notes: ['cedar', 'pepper', 'nuts', 'cream'], description: 'A medium-bodied, widely available Gurkha.',
    vitolas: [v('Robusto', 5, 52, 8), v('Toro', 6, 54, 9), v('Churchill', 7, 54, 10)] },
  { brand: 'Baccarat', name: 'Original', country: HON, wrapper: 'Connecticut Shade', binder: 'Mexican', filler: 'Honduran', strength: 'mild', year_introduced: 1871,
    flavor_notes: ['sweet', 'cream', 'cedar', 'vanilla'], description: 'Sweetened cap and a mild blend. The top-selling premium cigar in Honduras.',
    vitolas: [v('Rothschild', 5, 50, 5), v('Luchadores', 6, 43, 5), v('Toro', 6, 50, 6), v('Churchill', 7, 50, 7)] },
  { brand: 'Diamond Crown', name: 'Classic', country: DR, wrapper: 'Connecticut Shade (fermented)', binder: 'Dominican', filler: 'Dominican', strength: 'mild-medium', year_introduced: 1995,
    flavor_notes: ['cream', 'cedar', 'nuts', 'toast'], description: 'J.C. Newman\'s premium line, made by Fuente with five-year-aged tobacco.',
    vitolas: [v('Robusto No. 4', 4.5, 54, 13), v('Robusto No. 3', 5.5, 54, 14), v('No. 2', 6.5, 54, 16)] },
  { brand: 'Brick House', name: 'Classic', country: NIC, wrapper: 'Nicaraguan Havana Subido', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium', year_introduced: 2009,
    flavor_notes: ['cedar', 'earth', 'coffee', 'sweet spice'], description: 'J.C. Newman\'s Nicaraguan puro. One of the best values in the humidor.',
    vitolas: [v('Robusto', 5, 54, 7), v('Corona Larga', 6.25, 46, 7), v('Toro', 6, 52, 8), v('Mighty Mighty', 6.25, 60, 9), v('Churchill', 7.25, 50, 9)] },
  { brand: 'Brick House', name: 'Maduro', country: NIC, wrapper: 'Brazilian Arapiraca Maduro', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2012,
    flavor_notes: ['dark chocolate', 'coffee', 'earth', 'sweet spice'], description: 'The Brick House blend under a Brazilian maduro wrapper.',
    vitolas: [v('Robusto', 5, 54, 7), v('Toro', 6, 52, 8), v('Mighty Mighty', 6.25, 60, 9), v('Churchill', 7.25, 50, 9)] },
  { brand: 'Casa Magna', name: 'Colorado', country: NIC, wrapper: 'Nicaraguan Colorado', binder: 'Nicaraguan', filler: 'Nicaraguan', strength: 'medium-full', year_introduced: 2008,
    flavor_notes: ['pepper', 'cedar', 'earth', 'cocoa'], description: 'A Quesada and Plasencia collaboration that was Cigar of the Year in 2008.',
    vitolas: [v('Robusto', 5.5, 52, 8)] },

  // ── Cuba (Habanos; not sold in the US, listed for humidor logs and the passport) ─
  { brand: 'Cohiba (Cuba)', name: 'Siglo Series', country: CUBA, wrapper: 'Cuban', binder: 'Cuban', filler: 'Cuban (Vuelta Abajo)', strength: 'medium-full', year_introduced: 1992,
    flavor_notes: ['grass', 'honey', 'cedar', 'cream'], description: 'The Línea 1492. Cuban Cohibas are not legally sold in the US; listed for logging and travel humidors.',
    vitolas: [v('Siglo I', 4, 40, 25), v('Siglo II', 5, 42, 30), v('Siglo III', 6.1, 42, 38), v('Siglo IV', 5.6, 46, 42), v('Siglo V', 6.7, 43, 48), v('Siglo VI', 5.9, 52, 60)] },
  { brand: 'Cohiba (Cuba)', name: 'Behike', country: CUBA, wrapper: 'Cuban', binder: 'Cuban', filler: 'Cuban (with medio tiempo)', strength: 'full', year_introduced: 2010,
    flavor_notes: ['cocoa', 'cream', 'cedar', 'spice'], description: 'The most sought-after Cuban cigar, made with rare medio tiempo leaf.',
    vitolas: [v('BHK 52', 4.7, 52, 90), v('BHK 54', 5.7, 54, 110), v('BHK 56', 6.5, 56, 130)] },
  { brand: 'Cohiba (Cuba)', name: 'Línea Clásica', country: CUBA, wrapper: 'Cuban', binder: 'Cuban', filler: 'Cuban', strength: 'medium-full', year_introduced: 1966,
    flavor_notes: ['grass', 'cedar', 'honey', 'pepper'], description: 'The original Cohiba line, including the Robusto and Esplendidos.',
    vitolas: [v('Robusto', 4.9, 50, 45), v('Esplendidos', 7, 47, 60)] },
  { brand: 'Montecristo (Cuba)', name: 'Classic Line', country: CUBA, wrapper: 'Cuban', binder: 'Cuban', filler: 'Cuban', strength: 'medium-full', year_introduced: 1935,
    flavor_notes: ['cedar', 'cocoa', 'coffee', 'leather'], description: 'The best-selling Cuban brand. The No. 2 pyramid is the reference torpedo.',
    vitolas: [v('No. 5', 4, 40, 10), v('No. 4', 5.1, 42, 12), v('No. 3', 5.6, 42, 13), v('No. 1', 6.5, 42, 15), v('No. 2', 6.1, 52, 22), v('Petit Edmundo', 4.3, 52, 16), v('Edmundo', 5.3, 52, 19), v('Double Edmundo', 6.1, 50, 22)] },
  { brand: 'Partagás (Cuba)', name: 'Serie D and Serie P', country: CUBA, wrapper: 'Cuban', binder: 'Cuban', filler: 'Cuban', strength: 'full', year_introduced: 1845,
    flavor_notes: ['earth', 'pepper', 'leather', 'cedar'], description: 'The strong, earthy Havana. The Serie D No. 4 is the benchmark Cuban robusto.',
    vitolas: [v('Serie D No. 6', 3.5, 50, 10), v('Serie D No. 5', 4.3, 50, 13), v('Serie D No. 4', 4.9, 50, 16), v('Serie E No. 2', 5.5, 54, 20), v('Serie P No. 2', 6.1, 52, 20), v('Lusitanias', 7.6, 49, 28)] },
  { brand: 'Romeo y Julieta (Cuba)', name: 'Churchill Line', country: CUBA, wrapper: 'Cuban', binder: 'Cuban', filler: 'Cuban', strength: 'medium', year_introduced: 1875,
    flavor_notes: ['cedar', 'floral', 'cream', 'nuts'], description: 'Named for the brand\'s most famous fan. Balanced and aromatic.',
    vitolas: [v('Petit Churchills', 4, 50, 11), v('Short Churchills', 4.9, 50, 14), v('Wide Churchills', 5.1, 55, 16), v('Churchills', 7, 47, 22), v('Belicosos', 5.5, 52, 16), v('Exhibicion No. 4', 5, 48, 14)] },
  { brand: 'Hoyo de Monterrey (Cuba)', name: 'Epicure Line', country: CUBA, wrapper: 'Cuban', binder: 'Cuban', filler: 'Cuban', strength: 'mild-medium', year_introduced: 1865,
    flavor_notes: ['cream', 'cedar', 'grass', 'honey'], description: 'The lighter Havana. The Epicure No. 2 is the classic Cuban robusto for mornings.',
    vitolas: [v('Petit Robustos', 4, 50, 10), v('Epicure No. 2', 4.9, 50, 16), v('Epicure No. 1', 5.6, 46, 17), v('Epicure Especial', 5.6, 50, 20), v('Le Hoyo de San Juan', 5.9, 54, 24), v('Double Coronas', 7.6, 49, 30)] },
  { brand: 'Bolívar (Cuba)', name: 'Classic Line', country: CUBA, wrapper: 'Cuban', binder: 'Cuban', filler: 'Cuban', strength: 'full', year_introduced: 1902,
    flavor_notes: ['earth', 'pepper', 'leather', 'coffee'], description: 'Traditionally the strongest Havana marque.',
    vitolas: [v('Petit Coronas', 5.1, 42, 11), v('Royal Coronas', 4.9, 50, 15), v('Belicosos Finos', 5.5, 52, 18)] },
  { brand: 'Trinidad (Cuba)', name: 'Classic Line', country: CUBA, wrapper: 'Cuban', binder: 'Cuban', filler: 'Cuban', strength: 'medium', year_introduced: 1969,
    flavor_notes: ['cedar', 'cream', 'honey', 'spice'], description: 'Once a diplomatic gift, now a refined premium marque with pigtail caps.',
    vitolas: [v('Reyes', 4.3, 40, 15), v('Coloniales', 5.2, 44, 20), v('Vigia', 4.3, 54, 22), v('Fundadores', 7.5, 40, 35)] },
  { brand: 'H. Upmann (Cuba)', name: 'Magnum Line', country: CUBA, wrapper: 'Cuban', binder: 'Cuban', filler: 'Cuban', strength: 'medium', year_introduced: 1844,
    flavor_notes: ['cedar', 'cream', 'nuts', 'coffee'], description: 'Smooth and elegant. The Magnum 46 is a modern Cuban classic.',
    vitolas: [v('Half Corona', 3.5, 44, 9), v('Connoisseur No. 1', 5, 48, 16), v('Magnum 46', 5.6, 46, 18), v('Magnum 50', 6.3, 50, 22), v('Magnum 54', 4.7, 54, 20)] },
  { brand: 'Ramón Allones (Cuba)', name: 'Specially Selected', country: CUBA, wrapper: 'Cuban', binder: 'Cuban', filler: 'Cuban', strength: 'full', year_introduced: 1837,
    flavor_notes: ['dark fruit', 'earth', 'cocoa', 'spice'], description: 'A rich, full-flavored Havana robusto that ages beautifully.',
    vitolas: [v('Specially Selected', 4.9, 50, 15)] },
];

async function seedCatalog(db, { log = console.log } = {}) {
  const existing = await db.all('SELECT brand, name FROM cigars', []);
  const have = new Set(existing.map(r => `${r.brand.toLowerCase()}|${r.name.toLowerCase()}`));
  let cigars = 0, vitolas = 0;
  for (const c of CATALOG) {
    const key = `${c.brand.toLowerCase()}|${c.name.toLowerCase()}`;
    if (have.has(key)) continue;
    const r = await db.run(
      `INSERT INTO cigars (brand, name, country, wrapper, binder, filler, strength, flavor_notes, description, year_introduced)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id`,
      [c.brand, c.name, c.country, c.wrapper, c.binder, c.filler, c.strength, JSON.stringify(c.flavor_notes || []), c.description, c.year_introduced || null]
    );
    cigars++;
    for (const vt of c.vitolas || []) {
      await db.run('INSERT INTO vitolas (cigar_id, name, length, ring_gauge, msrp) VALUES (?, ?, ?, ?, ?)',
        [r.lastInsertRowid, vt.name, vt.length, vt.ring_gauge, vt.msrp]);
      vitolas++;
    }
  }
  if (cigars) log(`[catalog] added ${cigars} cigars and ${vitolas} vitolas (${CATALOG.length} in catalog)`);
  return { cigars, vitolas };
}

if (require.main === module) {
  const db = require('./db');
  const { initSchema, runMigrations } = require('./schema');
  (async () => {
    await initSchema();
    await runMigrations();
    console.log(await seedCatalog(db));
    process.exit(0);
  })().catch(err => { console.error(err); process.exit(1); });
}

module.exports = { CATALOG, seedCatalog };
